name: deploy
on:
  push:
    branches: [main]

concurrency:
  group: "deploy"
  cancel-in-progress: false

env:
    HOST: ${{ secrets.HOST }}
    PASSWORD: ${{ secrets.PASSWORD }}
    MAY_FIRST_AUTH_URL: ${{ secrets.MAY_FIRST_AUTH_URL }}
    USER: ${{ secrets.USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to remote server
        shell: bash
        run: curl --silent "$MAY_FIRST_AUTH_URL" -X POST -d "user_name=$USER" -d "user_pass=$PASSWORD" -d "action=grant"

      - name: Install sshpass
        shell: bash
        run: |
            sudo apt-get install sshpass
            SSH="sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$HOST"
            echo "SSH=${SSH}" >> $GITHUB_ENV

      - name: Update to latest main
        shell: bash
        run: $SSH "cd include/our-website; git pull origin main"

      - name: Install dependencies
        shell: bash
        run: $SSH "cd include/our-website; pnpm install"

      - name: Build to publish directory
        shell: bash
        run: $SSH "cd include/our-website; pnpm build --outDir /home/sites/381523/web/"
